// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIAUPQODr88qNS4gNpfMOGjpbh2xZE5FY',
    appId: '1:841533837208:web:bc223a290a3da4b7f8e5ed',
    messagingSenderId: '841533837208',
    projectId: 'flutter-chat-app-76c0c',
    authDomain: 'flutter-chat-app-76c0c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-76c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zo6NVFfWDt_aOtk-pjyD5bYIdJ8UuJ4',
    appId: '1:841533837208:android:4a630b2291162ebcf8e5ed',
    messagingSenderId: '841533837208',
    projectId: 'flutter-chat-app-76c0c',
    storageBucket: 'flutter-chat-app-76c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9befbO1G7dqmq7U2jmqNqx3MOx_WNac',
    appId: '1:841533837208:ios:dd3726ab09a14ddff8e5ed',
    messagingSenderId: '841533837208',
    projectId: 'flutter-chat-app-76c0c',
    storageBucket: 'flutter-chat-app-76c0c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9befbO1G7dqmq7U2jmqNqx3MOx_WNac',
    appId: '1:841533837208:ios:d02eb4a2dd641405f8e5ed',
    messagingSenderId: '841533837208',
    projectId: 'flutter-chat-app-76c0c',
    storageBucket: 'flutter-chat-app-76c0c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
